# NAME - ASWIN RAJ
# REG NO - 20MID0009
#CAMPUS - VIT VELLORE

**1)Assign your Name to variable name and Age to variable age. Make a Python program that prints your name and age.**


In [ ]:
x = "ASWIN RAJ"
y = 20
print("NAME AND AGE = ",x,y)

NAME AND AGE =  ASWIN RAJ 20


**2)X="Datascience is used to extract meaningful insights."Split the string**

In [ ]:
X="Datascience is used to extract meaningful insights."
splitwords = X.split()
print(splitwords)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


**3. Make a function that gives multiplication of two numbers**

In [ ]:
def mul(x,y):
  z = x*y
  return z
x = int(input("Input the value of x :"))
y = int(input("Input the value of y :"))  
print(mul(x,y))

Input the value of x :10
Input the value of y :5
50


**4. Create a Dictionary of 5 States with their capitals. also print the keys and values**

In [ ]:
X = {"Kerala":"Trivandrum","Tamil Nadu": "Chennai","West Bengal":"Kolkata","Andhra Pradesh":"Amravathi","Karnataka":"Banglore"}
print("States")
for state in X.keys():
  print(state)
print("\nCapital")  
for capital in X.values():
  print(capital)  

States
Kerala
Tamil Nadu
West Bengal
Andhra Pradesh
Karnataka

Capital
Trivandrum
Chennai
Kolkata
Amravathi
Banglore


**5. Create a list of 1000 numbers using range function.**

In [ ]:
A = list(range(1,1001))

**6. Create an identity matrix of dimension 4 by 4**

In [ ]:
import numpy as np
matrix = np.eye(4)
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**7. Create a 3x3 matrix with values ranging from 1 to 9**


In [ ]:
import numpy as np
matrix2 = np.arange(1,10).reshape(3,3)
print(matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**8. Create 2 similar dimensional array and perform sum on them**

In [ ]:
import numpy as np
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[10,11,12],[13,14,15],[16,17,18]])
sum = array1+array2
print(sum)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


**9. Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)**


In [ ]:
import pandas as pd

startdate = "2023-02-01"
enddate = "2023-03-01"

date_range = pd.date_range(start=startdate, end=enddate, closed='left')

for date in date_range:
    print(date.strftime('%d %B, %Y'))


01 February, 2023
02 February, 2023
03 February, 2023
04 February, 2023
05 February, 2023
06 February, 2023
07 February, 2023
08 February, 2023
09 February, 2023
10 February, 2023
11 February, 2023
12 February, 2023
13 February, 2023
14 February, 2023
15 February, 2023
16 February, 2023
17 February, 2023
18 February, 2023
19 February, 2023
20 February, 2023
21 February, 2023
22 February, 2023
23 February, 2023
24 February, 2023
25 February, 2023
26 February, 2023
27 February, 2023
28 February, 2023


<ipython-input-20-3bbcbe35e1e7>:6: FutureWarning: Argument `closed` is deprecated in favor of `inclusive`.
  date_range = pd.date_range(start=startdate, end=enddate, closed='left')


**10. Given a dictionary, convert it into corresponding dataframe and display it dictionary **= {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200,240]} 

In [ ]:
import pandas as pd
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
df = pd.DataFrame(dictionary)
print(df)

     Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240
